// 国际化-英文
module.exports = {
  overview: {
    shopSelect: 'Shop Select',
    ule: 'ULE MALL',
    today: 'Today',
    threeDays: 'Three Days',
    thirtyDays: 'Thirty Days',
    ninetyDays: 'Ninety Days',
    custom: 'Custom',
    lastWeek: 'LastWeek',
    startDate: 'Start Date',
    to: 'To',
    endDate: 'End Date',
    visitNumber: 'Access',
    totalOrder: 'Orders',
    totalGoods: 'Goods',
    totalMember: 'Members',
    totalDiscount: 'Discounts',
    seeMore: 'See More>>',
    order: 'Order',
    goods: 'Goods',
    member: 'Member',
    discount: 'Discount',
    times: 'Visits(time)',
    payPending: 'Pay Pending',
    deliverPending: 'Deliver Pending',
    delivered: 'Delivered',
    completed: 'Completed',
    cancelled: 'Cancelled',
    saleing: 'Saleing',
    stocking: 'Stocking',
    online: 'Online',
    offline: 'Offline',
    receivePending: 'Receive Pending',
    usePending: 'Use Pending',
    used: 'Used'
  },
  enterShop: {
    createShop: 'Create Shop',
    shopName: 'ShopName',
    host: 'Host',
    shopId: 'Shop Id',
    skuid: 'SKUID',
    createAt: 'CreateAt',
    handleAt: 'HandleAt',
    status: 'Status',
    operation: 'Operation',
    searchHolder: 'Enter shop name to search',
    delete: 'Delete',
    delConfirm: 'Are you sure you want to delete it?',
    tips: 'Tips',
    enter: 'Enter',
    cancel: 'Cancel',
    delSuccess: 'Delete Success',
    opaCancel: 'Operation cancelled',
    add: {
      createShop: 'Create Shop',
      brand: 'Brand',
      brandHolder: 'Please input brand information.',
      host: 'Host',
      hostHolder: 'Please input domain name information.',
      shopId: 'ShopId',
      shopIdHolder: 'Please enter shop Id',
      skuid: 'skuId',
      skuidHolder: 'Please enter skuId',
      brief: 'Brand introduction',
      briefHolder: 'Please input the brand profile information.',
      create: 'Immediate creation',
      cancel: 'Cancel',
      brandMsg: 'Please input brand name.',
      hostMsg: 'Please input host name.',
      shopIdMsg: 'Please enter shop Id',
      skuidMsg: 'Please enter skuId',
      briefMsg: 'The length is between 1 and 255 characters.',
      createConfirm: 'After the store is created, all data except the brand profile will be non-editable. Are you sure you want to create a store?',
      enter: 'Enter',
      createSuccess: 'New store success',
      opaCancel: 'Operation cancelled'
    },
    edit: {
      back: 'Back',
      baseMsg: 'Essential information',
      shopName: 'ShopName',
      shopId: 'ShopId',
      host: 'Host',
      skuid: 'SKUID',
      brand: 'Brand',
      linkman: 'Linkman',
      telephone: 'Telephone',
      email: 'Email',
      campany: 'Campany',
      address: 'Address',
      desc: 'Describe',
      descHolder: 'Please input the brand profile information.',
      save: 'Save',
      chart: 'Chart',
      trademark: 'Trade Mark',
      banner: 'Banner',
      authority: 'Authority',
      brief: 'Brief',
      noData: 'No Data',
      release: 'Release',
      descError: 'The length is between 1 and 255 characters.',
      editSuccess: 'Edit Success'
    },
    craw: {
      crawData: 'CrawData',
      refresh: 'Refresh',
      current: 'Current',
      totalResults: 'Total Results',
      totalPage: 'Total Page',
      pageSize: 'Page Size',
      currentPage: 'Current Page',
      updateSuccess: 'Success',
      updateFailed: 'Update Failed',
      notUpdate: 'Not Update',
      addSuccess: 'Add Success',
      addFailed: 'Add Failed',
      noData: 'No Data',
      date: 'Date',
      shopName: 'ShopName',
      goodsName: 'GoodsName',
      execStatus: 'Status',
      startCraw: 'Start crawling for merchandise....',
      crawEnd: 'Crawl goods end',
      crawStarted: 'The crawler program has started.',
      refreshed: 'Refreshed'
    }
  },
  goodsManagement: {
    all: 'All',
    sale: 'Saleing',
    stock: 'Stocking',
    shopSelect: 'Please choose shop',
    noLimit: 'Unlimited',
    searchHolder: 'Enter the name of the product to search.',
    goodsName: 'GoodsName',
    goodsId: 'GoodsId',
    price: 'Price',
    shopName: 'ShopName',
    status: 'Status',
    updateStatus: 'Update Status',
    timeStamp: 'Update Time',
    updateSuccess: 'Update Success',
    updateFailed: 'Update Failed',
    notUpdate: 'Not Update',
    addSuccess: 'Add Success',
    addFailed: 'Add Failed',
    detail: {
      back: 'Back',
      goodsDetail: 'Goods Detail',
      goodsId: 'GoodsId',
      goodsName: 'GoodsName',
      price: 'Price',
      status: 'Status',
      saleing: 'Saleing',
      stocking: 'Stocking',
      updateStatus: 'UpdateStatus',
      updateSuccess: 'UpdateSuccess',
      updateFailed: 'UpdateFailed',
      notUpdate: 'NotUpdate',
      addSuccess: 'AddSuccess',
      addFailed: 'AddFailed',
      shopName: 'ShopName',
      createAt: 'CreateAt',
      updateAt: 'UpdateAt',
      update: 'Update',
      sku: 'Skuid Message',
      colorSize: 'Color&Size',
      skuId: 'SkuId',
      stock: 'Stock',
      desc: 'Description',
      updateConfirm: 'Are you sure you want to update the data?',
      tips: 'Tips',
      enter: 'Enter',
      cancel: 'Cancel',
      updateSucces: 'Update Succes',
      opaCancel: 'Operation cancelled'
    }
  },
  orderManagement: {
    all: 'All',
    waitPay: 'Wait Pay',
    waitSend: 'Wait Send',
    alreadySend: 'Already Send',
    complate: 'Complate',
    cancel: 'Cancel',
    selectShopHolder: 'Please choose shop',
    noLimit: 'All',
    searchHolder: 'Enter the consignee name to search.',
    orderNo: 'OrderNo',
    status: 'Status',
    consignee: 'Consignee',
    goodsName: 'GoodsName',
    shopName: 'ShopName',
    createAt: 'CreateAt',
    detail: {
      back: 'Back',
      orderMessage: 'Order Message',
      orderNo: 'OrderNo',
      discountId: 'DiscountId',
      consignee: 'Consignee',
      shopName: 'ShopName',
      payWay: 'PayWay',
      payAfter: 'PayAfter',
      weixin: 'Weixin',
      zhifubao: 'ZhiFuBao',
      orderStatus: 'OrderStatus',
      waitPay: 'WaitPay',
      waitSend: 'WaitSend',
      alreadySend: 'AlreadySend',
      complate: 'Complate',
      cancel: 'Cancel',
      discount: 'Discount',
      amount: 'Amount',
      createAt: 'CreateAt',
      goodsMsg: 'GoodsMsg',
      goodsName: 'GoodsName',
      tagPrice: 'Tag Price',
      color: 'Color',
      size: 'Size',
      number: 'Number',
      sendMsg: 'SendMsg',
      noData: 'NoData',
      rMan: 'Consignee',
      address: 'Address',
      telephone: 'Telephone',
      distributionMsg: 'DistributionMsg',
      courierNo: 'CourierNo',
      company: 'Company',
      basicMsg: 'Basic Message'
    }
  },
  memberManagement: {
    areaHolder: 'Filtering the input area name',
    all: 'All',
    online: 'Online',
    offline: 'Offline',
    searchHolder: 'Enter user account / cell phone number to search.',
    account: 'Account',
    name: 'Name',
    status: 'Status',
    sex: 'Sex',
    address: 'Address',
    province: 'Province',
    city: 'City',
    school: 'School',
    campus: 'Campus',
    createAt: 'CreateAt',
    freeze: 'Freeze',
    operation: 'Operation',
    male: 'Male',
    female: 'Female',
    normal: 'Normal',
    freezed: 'Freezed',
    enable: 'Enable',
    disable: 'Disable',
    del: 'Delete',
    delConfirm: 'Delete Confirm?',
    tips: 'Tips',
    enter: 'Enter',
    cancel: 'Cancel',
    delSuccess: 'Delete Success',
    opaCancel: 'Operation cancelled',
    enableConfirm: 'Are you sure you want to enable it?？',
    disableConfirm: 'Are you sure you want to disable it?？',
    enableSuccess: 'Enable Success',
    disableSuccess: 'Disable Success',
    detail: {
      back: 'Back',
      basicMessage: 'Basic Message',
      memberId: 'MemberId',
      account: 'Account',
      freezeStatus: 'Freeze Status',
      normal: 'Normal',
      freezed: 'Freezed',
      status: 'Status',
      online: 'Online',
      offline: 'Offline',
      province: 'Province',
      city: 'City',
      school: 'School',
      campus: 'Campus',
      createAt: 'CreateAt',
      updateAt: 'UpdateAt',
      orderMsg: 'Order Message',
      noData: 'No Data',
      discountMsg: 'Discount Message',
      visitMsg: 'Visit Message'
    }
  },
  discountManagement: {
    all: 'All',
    receivePending: 'Receive Pending',
    usePending: 'Use Pending',
    used: 'Used',
    completed: 'Completed',
    shopSelectHolder: 'Please choose shop',
    noLimit: 'All',
    searchKey: 'Input membership account for search',
    discountId: 'DiscountId',
    shopName: 'Shop',
    memberAccount: 'Member',
    status: 'Status',
    type: 'Discount',
    discount1: 'One Type',
    discount2: 'Two Type',
    discount3: 'Three Type',
    discount4: 'Four Type',
    discount5: 'Five Type',
    createAt: 'CreateAt',
    detail: {
      discountDeatil: 'Discount Deatil',
      discountId: 'DiscountId',
      order: 'Order',
      memberAccount: 'Member',
      shopName: 'Shop',
      discount: 'Discount',
      discount1: 'One Type',
      discount2: 'Two Type',
      discount3: 'Three Type',
      discount4: 'Four Type',
      discount5: 'Five Type',
      status: 'Status',
      receivePending: 'Receive Pending',
      usePending: 'Use Pending',
      used: 'Used',
      completed: 'Completed',
      createAt: 'CreateAt',
      back: 'Back'
    }
  },
  userManagement: {
    add: 'Add',
    del: 'Delete',
    selectHolder: '请选择用户类型',
    noLimit: '不限',
    tenant: '租户',
    normal: '普通用户',
    searchHolder: '输入用户账号/姓名进行搜索',
    account: '用户账号',
    roleName: '角色',
    name: '姓名',
    telephone: '联系电话',
    desc: '描述',
    deleteConfirm: '确定要删除已选用户吗?',
    tips: '提示',
    enter: '确定',
    cancel: '取消',
    delSuccess: '删除成功',
    opaCancel: '操作已取消',
    addEdit: {
      role: '角色',
      roleSelect: '请选择角色',
      account: '用户账号',
      accountHolder: '请输入用户账号-最短3个字符最长不超过16个字符',
      name: '姓名',
      nameHolder: '请输入姓名',
      sex: '性别',
      male: '男',
      female: '女',
      telephone: '联系电话',
      telephoneHolder: '联系电话',
      email: '电子邮件',
      emailHolder: '电子邮件',
      desc: '描述',
      descHolder: '请输入描述信息',
      create: '立即创建',
      save: '保存修改',
      cancel: '取消',
      add: '添加用户',
      roleError: '请选择角色',
      nameError: '长度在 1 到 32 个字符',
      descError: '长度在 1 到 255 个字符',
      addUser: '添加用户',
      editUser: '编辑用户',
      addSuccess: '用户添加成功',
      editSuccess: '用户编辑成功'
    }
  },
  roleManagement: {
    add: '添加',
    del: '删除',
    searchHolder: '输入角色名称进行搜索',
    name: '角色名称',
    desc: '描述',
    authArr: '权限列表',
    delConfirm: '确定要删除已选角色吗?',
    tips: '提示',
    enter: '确定',
    cancel: '取消',
    delSuccess: '删除成功',
    opaCancel: '操作已取消',
    addEdit: {
      roleName: '角色名称',
      roleNameHolder: '请输入角色名称',
      auth: '菜单权限',
      authHolder: '输入关键字进行过滤',
      desc: '描述',
      descHolder: '请输入描述信息',
      create: '立即创建',
      save: '保存修改',
      cancel: '取消',
      addRole: '添加角色',
      roleNameError: '请输入角色名称',
      roleLengthError: '长度在 1 到 32 个字符',
      descError: '长度在 1 到 255 个字符',
      editRole: '编辑角色',
      addSuccess: '角色添加成功',
      editSuccess: '角色编辑成功'
    }
  },
  taskManagement: {
    taskTypeSelect: '请选择定时任务类型',
    noLimit: '不限',
    tenant: '租户',
    system: '系统',
    searchHolder: '输入定时任务名称进行搜索',
    taskName: '名称',
    tag: '类型',
    systemTask: '系统任务',
    tenantTask: '租户任务',
    tenantName: '租户',
    rule: '执行时间',
    ready: '就绪状态',
    abled: '已启用',
    disabled: '未启用',
    status: '运行状态',
    runing: '运行中',
    pending: '挂起中',
    desc: '描述',
    detail: {
      taskDetail: '定时任务详情',
      name: '定时任务名称',
      tenantName: '租户',
      timeType: '时间类型',
      day: '每天',
      week: '每周',
      month: '每月',
      type: '类型',
      tenant: '租户任务',
      system: '系统任务',
      module: '所属模块',
      handle: '处理函数',
      ready: '就绪状态',
      abled: '已启用',
      disabled: '未启用',
      rule: '定时规则',
      status: '运行状态',
      runing: '运行中',
      pending: '挂起中',
      desc: '描述',
      createAt: '创建时间',
      updateAt: '最近更新时间',
      back: '返回'
    }
  },
  fileManagement: {
    all: '全选',
    del: '删除',
    dir: '文件夹',
    file: '文件',
    fileName: '文件名称',
    type: '类型',
    path: '路径',
    createAt: '创建时间',
    noData: '暂无数据',
    total: '共计',
    obj: '个对象'
  },
  msgManagement: {},
  login: {
    uleMall: '优乐商城',
    accountLogin: '账号登录',
    condition: '验证身份后进行登录',
    forByPhoneDes: '如果手机停用或原先手机号不能正常使用，请进入',
    linkUs: '联系我们',
    linkService: '页面联系我们客服人员。',
    forget: '忘记密码',
    accountHolder: '请输入账户名',
    pwdHolder: '输入新密码',
    read: '我已同意',
    userBook: '《优乐商城用户协议》',
    login: '登录',
    userBookSimble: '优乐帐号用户协议',
    aboutUs: '关于优乐帐号与隐私的声明',
    footerTxt: 'Copyright&nbsp;©&nbsp;2011-2018&nbsp;&nbsp;南京优乐校园电子商务有限公司&nbsp;&nbsp;版权所有&nbsp;&nbsp;保留一切权利&nbsp;&nbsp;苏B2-20070200号&nbsp;|&nbsp;\n' + ' 苏ICP备09062682号-9',
    forgetPwd: {
      uleMall: '优乐校园',
      forgetTitle: '忘记密码',
      tips: '提示：点击图片可刷新验证码',
      accountHolder: '请输入账号',
      validCodeHolder: '请输入验证码',
      nextStep: '下一步',
      cancel: '取消',
      forByPhoneSubTitle: '验证身份后设置新密码',
      forByPhoneDes: '如果您有其他设备使用此帐号，设置新密码后需重新登录，以确保正常使用华为服务。',
      forCode: '获取验证码',
      validCode: '验证码',
      newPwdHolder: '输入新密码',
      confirmPwdHolder: '输入确认密码',
      enter: '确定',
      userBook: '优乐帐号用户协议',
      aboutUs: '关于优乐帐号与隐私的声明',
      linkUs: '联系我们',
      footerTxt: 'Copyright&nbsp;©&nbsp;2011-2018&nbsp;&nbsp;南京优乐校园电子商务有限公司&nbsp;&nbsp;版权所有&nbsp;&nbsp;保留一切权利&nbsp;&nbsp;苏B2-20070200号&nbsp;|&nbsp;\n' + ' 苏ICP备09062682号-9',
      pwdRule1: '包含数字，字母及特殊字符且8到12位',
      pwdRule2: '两次输入密码不一致',
      verText: '获取验证码',
      backPwdTxt: '两次密码输入不一致',
      backPwdSuccess: '修改密码成功',
      sendAfer1: '60s后发送',
      sendAfter2: 's后发送',
      sendAgain: '重新发送'
    },
    firstLogin: {
      dialogTitle: '绑定手机号-首次登录',
      tips: '验证码将会发送至您的手机',
      telephoneHolder: '请输入手机号码',
      getValidCode: '获取验证码',
      alreadySend: '已发送验证码至您的账号',
      validCodeHolder: '请输入手机验证码',
      originalPwdHolder: '请输入旧密码',
      newPwdHolder: '请输入新密码',
      updatePwd: '修改密码',
      elDialogTitle: '修改密码',
      verText: '获取验证码',
      sendAfer1: '60s后发送',
      sendAfter2: 's后发送',
      sendAgain: '重新发送',
      opaSuccess: '绑定手机并修改密码成功'
    }
  },
  protal: {
    product: '产品与服务',
    productTitle: '精准.可控.高效.可持续',
    way: '可控的商品信息与品牌推广渠道',
    wayTitle: '使用云服务ECS、VPC、EVS、AS、ELB部署应用，搭建论坛网站',
    mark: '精准的市场定位',
    markTitle: '使用微服务开发框架，将电商应用从原生Spring Boot和Go-kit迁移并部署到ServiceStage平台上',
    data: '数据采集与量化分析',
    dataTitle: '使用机器学习服务，预测餐厅未来的销售量，为开设新餐厅提供决策依据。',
    cooperative: '合作伙伴展示',
    cooperativeTitle: '共建和谐共赢的云生态，实现快速发展',
    book: {
      title: '声明.协议.文档',
      statement: '法律声明',
      userBook: '优乐用户协议',
      linkUsTxt: '联系我们',
      linkUs: {
        title: '联系我们',
        address: '联系地址',
        forByPhoneDes: '如果手机停用或原先手机号不能正常使用，请进入联系我们页面联系我们客服人员。',
        linkmanTxt: '联系人',
        linkman: '董纪国',
        telTxt: '联系电话',
        tel: '18205185737'
      }
    }
  },
  frame: {
    visitToday: '当日访问数据-点击可刷新',
    footerTxt: '©2017 苏州万店掌网络科技有限公司 苏ICP备16028066',
    header: {
      yleMall: '优乐校园',
      navigation: '网站导航',
      userBook: '协议声明',
      download: '下载中心',
      android: '安卓客户端',
      androidVersion: 'v1.0.0',
      ios: 'IOS客户端',
      iosVersion: 'v1.0.0',
      agreeBook: '用户手册',
      zh: '中文（简体）',
      en: 'English（英文）',
      personal: '个人中心',
      msg: '消息',
      loginout: '退出',
      login: '登录'
    },
    foolter: {
      copyright1: '版权所有 © 华为软件技术有限公司 2018',
      copyright2: '保留一切权利',
      copyright3: '苏ICP备17040376号-5',
      copyright4: '苏B2-20130048号',
      statement: '法律声明',
      policy: '隐私政策声明',
      aboutUs: '关于我们',
      linkUs: '联系我们',
      userBook: '优乐商城用户协议',
      bottomArea: '苏公网安备 32011402010008号'
    }
  },
  personal: {
    titleTxt: '个人资料',
    account: '账号',
    name: '用户姓名',
    sex: '性别',
    male: '男',
    female: '女',
    telephone: '手机号码',
    emial: '邮箱',
    save: '保 存',
    safety: '账号安全',
    validPhone: '验证手机',
    yourPhone: '您的手机',
    phoneChangeTxt: '若已丢失或停用，请立即更换，避免账号被盗',
    change: '更换手机号',
    setPwd: '密码设置',
    setPwdTips: '安全性高的密码可以使账号更安全，建议您定期更换密码，且设置包含数字、字母及特殊字符且8位以上',
    update: '修 改',
    emailError: '请输入正确的邮箱地址',
    emailLengthLimit: '不能超过30个字',
    updateSuccess: '修改成功',
    phoneModal: {
      changePhone: '更换手机号',
      telephone: '新手机号',
      validCode: '验证码',
      phoneInputHolder: '请输入手机验证码',
      enter: '确 定',
      cancel: '取 消',
      verText: '获取验证码',
      updateSuccess: '手机号修改成功',
      send1: '60s后发送',
      send2: 's后发送',
      sendAgain: '重新发送'
    },
    pwdModal: {
      updatePWd: '修改密码',
      oldPwd: '旧密码',
      newPwd: '新密码',
      confirmPwd: '确认密码',
      enter: '确 定',
      cancel: '取 消',
      pwdVaild1: '包含数字，字母及特殊字符且8到12位',
      pwdValid2: '两次输入密码不一致',
      updateSuccess: '已成功修改密码，请重新登录'
    }
  },
  common: {
    length25Error: '长度不能超过25个字节',
    sexSelectError: '请选择性别',
    checkSpecialChar: '内容含有特殊字符',
    validatePhone: '请输入正确的手机号码',
    validateCode: '请输入正确的验证码，六位数字',
    validatePwd: '包含数字，字母及特殊字符且8到20位',
    validateAccount: '最短3个字符最长不超过16个字符',
    validateHost: '格式错误',
    validateShopId: '格式错误',
    validateSkuId: '格式错误',
    loadding: '加载中...',
    treeLoadding: '加载中...'
  }
}
