// 国际化-英文
module.exports = {
  overview: {
    shopSelect: 'Shop Select',
    ule: 'ULE MALL',
    today: 'Today',
    threeDays: 'Three Days',
    thirtyDays: 'Thirty Days',
    ninetyDays: 'Ninety Days',
    custom: 'Custom',
    lastWeek: 'LastWeek',
    startDate: 'Start Date',
    to: 'To',
    endDate: 'End Date',
    visitNumber: 'Access',
    totalOrder: 'Orders',
    totalGoods: 'Goods',
    totalMember: 'Members',
    totalDiscount: 'Discounts',
    seeMore: 'See More>>',
    order: 'Order',
    goods: 'Goods',
    member: 'Member',
    discount: 'Discount',
    times: 'Visits(time)',
    payPending: 'Pay Pending',
    deliverPending: 'Deliver Pending',
    delivered: 'Delivered',
    completed: 'Completed',
    cancelled: 'Cancelled',
    saleing: 'Saleing',
    stocking: 'Stocking',
    online: 'Online',
    offline: 'Offline',
    receivePending: 'Receive Pending',
    usePending: 'Use Pending',
    used: 'Used'
  },
  enterShop: {
    createShop: 'Create Shop',
    shopName: 'ShopName',
    host: 'Host',
    shopId: 'Shop Id',
    skuid: 'SKUID',
    createAt: 'CreateAt',
    handleAt: 'HandleAt',
    status: 'Status',
    operation: 'Operation',
    searchHolder: 'Enter shop name to search',
    delete: 'Delete',
    delConfirm: 'Are you sure you want to delete it?',
    tips: 'Tips',
    enter: 'Enter',
    cancel: 'Cancel',
    delSuccess: 'Delete Success',
    opaCancel: 'Operation cancelled',
    add: {
      createShop: 'Create Shop',
      brand: 'Brand',
      brandHolder: 'Please input brand information.',
      host: 'Host',
      hostHolder: 'Please input domain name information.',
      shopId: 'ShopId',
      shopIdHolder: 'Please enter shop Id',
      skuid: 'skuId',
      skuidHolder: 'Please enter skuId',
      brief: 'Brand introduction',
      briefHolder: 'Please input the brand profile information.',
      create: 'Immediate creation',
      cancel: 'Cancel',
      brandMsg: 'Please input brand name.',
      hostMsg: 'Please input host name.',
      shopIdMsg: 'Please enter shop Id',
      skuidMsg: 'Please enter skuId',
      briefMsg: 'The length is between 1 and 255 characters.',
      createConfirm: 'After the store is created, all data except the brand profile will be non-editable. Are you sure you want to create a store?',
      enter: 'Enter',
      createSuccess: 'New store success',
      opaCancel: 'Operation cancelled'
    },
    edit: {
      back: 'Back',
      baseMsg: 'Essential information',
      shopName: 'ShopName',
      shopId: 'ShopId',
      host: 'Host',
      skuid: 'SKUID',
      brand: 'Brand',
      linkman: 'Linkman',
      telephone: 'Telephone',
      email: 'Email',
      campany: 'Campany',
      address: 'Address',
      desc: 'Describe',
      descHolder: 'Please input the brand profile information.',
      save: 'Save',
      chart: 'Chart',
      trademark: 'Trade Mark',
      banner: 'Banner',
      authority: 'Authority',
      brief: 'Brief',
      noData: 'No Data',
      release: 'Release',
      descError: 'The length is between 1 and 255 characters.',
      editSuccess: 'Edit Success'
    },
    craw: {
      crawData: 'CrawData',
      refresh: 'Refresh',
      current: 'Current',
      totalResults: 'Total Results',
      totalPage: 'Total Page',
      pageSize: 'Page Size',
      currentPage: 'Current Page',
      updateSuccess: 'Success',
      updateFailed: 'Update Failed',
      notUpdate: 'Not Update',
      addSuccess: 'Add Success',
      addFailed: 'Add Failed',
      noData: 'No Data',
      date: 'Date',
      shopName: 'ShopName',
      goodsName: 'GoodsName',
      execStatus: 'Status',
      startCraw: 'Start crawling for merchandise....',
      crawEnd: 'Crawl goods end',
      crawStarted: 'The crawler program has started.',
      refreshed: 'Refreshed'
    }
  },
  goodsManagement: {
    all: 'All',
    sale: 'Saleing',
    stock: 'Stocking',
    shopSelect: 'Please choose shop',
    noLimit: 'Unlimited',
    searchHolder: 'Enter the name of the product to search.',
    goodsName: 'GoodsName',
    goodsId: 'GoodsId',
    price: 'Price',
    shopName: 'ShopName',
    status: 'Status',
    updateStatus: 'Update Status',
    timeStamp: 'Update Time',
    saleing: 'saleing',
    stocking: 'stocking',
    create: 'Create',
    updateSuccess: 'Update Success',
    updateFailed: 'Update Failed',
    notUpdate: 'Not Update',
    addSuccess: 'Add Success',
    addFailed: 'Add Failed',
    detail: {
      back: 'Back',
      basicMessage: 'Basic Message',
      goodsId: 'GoodsId',
      goodsName: 'GoodsName',
      price: 'Price',
      status: 'Status',
      saleing: 'Saleing',
      stocking: 'Stocking',
      create: 'Create',
      updateStatus: 'UpdateStatus',
      updateSuccess: 'UpdateSuccess',
      updateFailed: 'UpdateFailed',
      notUpdate: 'NotUpdate',
      addSuccess: 'AddSuccess',
      addFailed: 'AddFailed',
      shopName: 'ShopName',
      createAt: 'CreateAt',
      updateAt: 'UpdateAt',
      update: 'Update',
      sku: 'Skuid Message',
      colorSize: 'Color&Size',
      skuId: 'SkuId',
      stock: 'Stock',
      desc: 'Description',
      updateConfirm: 'Are you sure you want to update the data?',
      tips: 'Tips',
      enter: 'Enter',
      cancel: 'Cancel',
      opaCancel: 'Operation cancelled'
    }
  },
  orderManagement: {},
  memberManagement: {},
  discountManagement: {},
  userManagement: {},
  roleManagement: {},
  taskManagement: {},
  fileManagement: {},
  msgManagement: {},
  iam: {},
  protal: {},
  frame: {},
  personal: {}
}
