// 国际化-英文
module.exports = {
  overview: {
    shopSelect: 'Shop Select',
    ule: 'ULE MALL',
    today: 'Today',
    threeDays: 'Three Days',
    thirtyDays: 'Thirty Days',
    ninetyDays: 'Ninety Days',
    custom: 'Custom',
    lastWeek: 'LastWeek',
    startDate: 'Start Date',
    to: 'To',
    endDate: 'End Date',
    visitNumber: 'Access',
    totalOrder: 'Orders',
    totalGoods: 'Goods',
    totalMember: 'Members',
    totalDiscount: 'Discounts',
    seeMore: 'See More',
    order: 'Order',
    goods: 'Goods',
    member: 'Member',
    discount: 'Discount',
    times: 'Visits(time)',
    payPending: 'Pay Pending',
    deliverPending: 'Deliver Pending',
    delivered: 'Delivered',
    completed: 'Completed',
    cancelled: 'Cancelled',
    saleing: 'Saleing',
    stocking: 'Stocking',
    online: 'Online',
    offline: 'Offline',
    receivePending: 'Receive Pending',
    usePending: 'Use Pending',
    used: 'Used'
  },
  enterShop: {
    createShop: '',
    shopName: '',
    host: '',
    shopId: '',
    skuid: '',
    createAt: '',
    handleAt: '',
    status: '',
    operation: '',
    searchHolder: '',
    delete: '',
    delConfirm: '',
    tips: '',
    enter: '',
    cancel: '',
    delSuccess: '',
    opaCancel: '',
    add: {
      brand: '',
      brandHolder: '',
      host: '',
      hostHolder: '',
      shopId: '',
      shopIdHolder: '',
      skuid: '',
      skuidHolder: '',
      brief: '',
      briefHolder: '',
      create: '',
      cancel: '',
      brandMsg: '',
      hostMsg: '',
      shopIdMsg: '',
      skuidMsg: '',
      briefMsg: '',
      delConfirm: '',
      enter: '',
      createSuccess: '',
      opaCancel: ''
    },
    edit: {
      back: '',
      baseMsg: '',
      shopName: '',
      shopId: '',
      host: '',
      skuid: '',
      brand: '',
      linkman: '',
      temephone: '',
      email: '',
      campany: '',
      address: '',
      desc: '',
      descHolder: '',
      save: '',
      chart: '',
      trademark: '',
      banner: '',
      authority: '',
      brief: '',
      noData: '',
      release: '',
      descError: '',
      editSuccess: ''
    },
    craw: {
      crawData: '',
      refresh: '',
      current: '',
      totalResults: '',
      totalPage: '',
      pageSize: '',
      currentPage: '',
      updateSuccess: '',
      updateFailed: '',
      notUpdate: '',
      addSuccess: '',
      addFailed: '',
      noData: '',
      date: '',
      shopName: '',
      goodsName: '',
      execStatus: '',
      startCraw: '',
      crawEnd: '',
      crawStarted: '',
      refreshed: ''
    }
  },
  goodsManagement: {},
  orderManagement: {},
  memberManagement: {},
  discountManagement: {},
  userManagement: {},
  roleManagement: {},
  taskManagement: {},
  fileManagement: {},
  msgManagement: {},
  iam: {},
  protal: {},
  frame: {},
  personal: {}
}
